version: '3'
services:
  mariadb:
    image: mariadb
    container_name: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_USER: agente
      MARIADB_USER_PASSWORD: 0traClave
      MARIADB_DATABASE: PEPS
    volumes:
      - ./mariadb_data:/var/lib/mysql
    user: mysql
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      - PMA_HOST=mariadb
    ports:
      - 9093:80
    depends_on:
      - mariadb
  apache:
    build: ./apache
    container_name: apache
    volumes:
      - ./apache/static:/var/www/html:ro
    ports:
      - "7777:80"
    restart: unless-stopped
    depends_on:
      - python
  python:
    build: .
    container_name: python
    environment:
      PYTHONBUFFERED: 1
      DB_USERNAME: root
      DB_PASSWORD: example
      DB_DATABASE: PEPS
      DB_HOST: mariadb
      DB_PORT: 3306
      PORT: 8080
      HOST: 0.0.0.0
    ports:
      - 9094:8080
    depends_on:
        - mariadb